spring:
  application:
    name: minio_demo_hd
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/huadi?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    username: root
    password: TZR112177...
  servlet:
    multipart:
      enabled: true
      max-file-size: 1000MB
      max-request-size: 1000MB

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

# MinIO配置
minio:
  endpoint: http://127.0.0.1:9005
  accessKey: admin
  secretKey: admin112177
#  bucket: user-bucket

server:
  port: 8090







